name = "EcologicalNetworksPlots"
uuid = "1a178c60-9a7b-11e8-2a1a-8dce3be9a50c"
authors = ["Timothée Poisot <timothee.poisot@umontreal.ca>"]
version = "0.0.1"

[deps]
EcologicalNetworks = "26cd3c7c-942f-11e8-1e85-357945f36438"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
