name = "EcologicalNetworksPlots"
uuid = "1a178c60-9a7b-11e8-2a1a-8dce3be9a50c"
authors = ["Timothée Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.0"

[deps]
EcologicalNetworks = "26cd3c7c-942f-11e8-1e85-357945f36438"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
